### PR TITLE
Litecoin: Adjust splashscreen for testnet/regtest

### PR DESCRIPTION
**Pull request by thrasher-**
This fixes https://github.com/litecoin-project/litecoin/issues/286

The original Litecoin icon is mainly grey and doesn't support modification via hue/saturation. A new splash screen is added which is green by default for testnet and supports hue modification to a colour similar to Bitcoin's regtest. Unfortunately Qt doesn't support negative saturation values, otherwise this single splash screen could be used for all mainnet, testnet and regtest icons/splash screens.

Example regtest colour: http://imgur.com/a/pOzHl

### CODE REVIEW

**Comment by thrasher-** [comment]
results

**Comment by wangxinxi** [comment]
How about something like this http://amin-ahmadi.com/2016/06/05/change-hue-image-qt/?

**Comment by thrasher-** [comment]
It pretty much does that already, except using setHsl instead of setHsv. http://doc.qt.io/qt-4.8/qcolor.html This documentation states that saturation with both functions can only be a value between 0 and 255.

**Comment by wangxinxi** [comment]
Got it. The image and code looks good to me.

**Pull request merged**
