### PR TITLE
Fixed getbalance command

### PR DESCRIPTION
**Pull request by thrasher-**
Rebased-by: Adrian Gallagher <thrasher@addictionsoftware.com>
Rebased-from: 7d6a85ab5b1dc96e0f3f6f835f27bb81ba2af919 Bitcoin PR #6276

### CODE REVIEW

**Comment by wtogami** [comment]
Above your Rebased lines include the original text from his commit.

git commit --amend
git push remotename branchname --force

The --force will update the branch and this PR.

**Comment by thrasher-** [comment]
Done

**Comment by wtogami** [comment]
Make the first line of the commit message identical to the original.  Sorry for being pedantic.  It is just proper procedure when you take someone else's commit.

**Comment by thrasher-** [comment]
Closed as this will be merged from upstream.

**Pull request closed without merging**
