### PR TITLE
Support for SmartOS

### PR DESCRIPTION
**Pull request by epipenau**
Litecoind compiles and runs on SmartOS as a result of these patches.

These patches may also work on Solaris/illumos however it is unconfirmed.  If somebody would like to test, please do so and report back to us.

I haven't patched the QT client for building yet.

### CODE REVIEW

**Comment by wtogami** [comment]
Does Bitcoin Core 0.10rc3 build on SmartOS?  0.8 is in maintenance only mode right now and we are going with 0.10 next.  I'll take a look at your patch though.

**Comment by epipenau** [comment]
I believe it does.  I will try right now to confirm.  When are you going to switch to 0.10 ?

**Comment by wtogami** [comment]
Hopefully during this next week.

**Comment by epipenau** [comment]
configure fails with 

checking for Berkeley DB C++ headers... /opt/local/include/db4/
checking for main in -ldb_cxx-4.8... no
checking for main in -ldb_cxx... no
configure: error: libdb_cxx missing, Bitcoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)


and I’m not sure why.

this is the contents of 

[root@masked ~/bitcoin]# ls /opt/local/include/db4/
db.h  db_185.h  db_cxx.h

any insight would be greatly appreciated.

**Comment by wtogami** [comment]
Please fix that for Bitcoin.  It will automatically work when I import it into Litecoin.

**Comment by epipenau** [comment]
if i edit ./configure and change 
for searchlib in db_cxx-4.8 db_cxx; do

to

for searchlib in db_cxx-4.8 db_cxx db4_cxx-4.8 db4_cxx; do

it works.

but i don’t know how to add that to configure.ac or wherever it goes so that it’s added to the ./configure that is generated by ./autogen.sh

**Comment by epipenau** [comment]
SmartOS doesn’t have hex dump, it only has od.

So I also have to do HEXDUMP=“/usr/local/bin/od” ./configure

and then ./configure succeeds.

I have run make and it is going well.

alert.cpp has now failed due to the inclusion of net/if.h which has a struct map in it making the std map ambiguous.  This is the same as 0.8.  I can simply remove the net/if.h include from alert.cpp to proceed.

**Comment by wtogami** [comment]
Explain the configure script fix that allows it to work in a bitcoin issue, cfields will know how to fix it permanently.  I am not changing it in 0.8.  Closing here.

**Comment by epipenau** [comment]
what i did was edit bitcoin/build-aux/m4/bitcoin_find_bdb48.m4 and changed for searchlib in db_cxx-4.8 db_cxx; do --- to for searchlib in db_cxx-4.8 db_cxx db4_cxx-4.8 db4_cxx; do

next i edited bitcoin/configure.ac to replace hexdump with od.  (i've been advised this should probably be done anyway as od is POSIX compliant and hexdump is not.)

configure.ac
- AC_PATH_PROG(HEXDUMP,hexdump)
+ AC_PATH_PROG(OD,od)

and changed this from hexdump to od

if test x$OD = x; then
    AC_MSG_ERROR(od is required for tests)
  fi

I also changed the actual hexdump tests that were in a Makefile of some sort but now I can't find it...  i changed something like @HEXDUMP@ to @OD@, left the -v flags and changed the -e flags to -t.  im not sure if it ran, im not sure where it's called but it didn't error.

i edited bitcoin/src/compat.h from

#include <sys/types.h>
#include <net/if.h>
#include <netinet/in.h>

to::

#include <sys/types.h>
#define map junkmap
#include <net/if.h>
#undef map
#include <netinet/in.h>

now.... i think that is everything i changed.  a whole heap compiles but stops at rpcserver with another ambiguous map
rpcserver.cpp:43:8: error: reference to 'map' is ambiguous

im about to look at fixing that now, there is a struct map in net/if.h that makes the std::map ambiguous and i just need to treat it somewhat like i did in compat.h, but this one is proving to be a bit more involved.

**Comment by epipenau** [comment]
here we go:

https://github.com/bitcoin/bitcoin/issues/5659

**Pull request closed without merging**
