### PR TITLE
Litecoin: Cosmetic string changes.

### PR DESCRIPTION
**Pull request by thrasher-**

### CODE REVIEW

**Comment by bardiharborow** [comment]
Won't this break compatibility with all existing signatures?

**Comment by thrasher-** [comment]
No it won't, we've used this since pre 0.8x. Thanks for checking though!

**Comment by bardiharborow** [comment]
Oh, is this part of a re-fork from Bitcoin 0.10?

**Comment by thrasher-** [comment]
Yeah, this version is based off Bitcoin's 0.10 version.

**Pull request merged**
