### PR TITLE
Litecoin: Reduce min relay fee from 1 lite/kB to 0.1 lite/kB.

### PR DESCRIPTION
**Pull request by coblee**
Min transaction fee is still 1 lite/kB.

### CODE REVIEW

**Comment by losh11** [comment]
ACK - will go over tests later.

**Comment by losh11** [comment]
@coblee can you fix the broken tests? Travis doesn't seem to be reporting all failing tests correctly.

**Comment by coblee** [comment]
Thrasher said he would fix then

**Comment by thrasher-** [comment]
Closed in favour of https://github.com/litecoin-project/litecoin/commit/98d755d14034f116f6da83049ccc2d20fe04cb38

**Pull request closed without merging**
