### PR TITLE
Litecoin: Rename mLTC/μLTC to lites/photons.

### PR DESCRIPTION
**Pull request by coblee**
Make denominations more user friendly with lites and photons

### CODE REVIEW

**Comment by anronin** [comment]
What about lites/lumens ?

**Comment by losh11** [comment]
NACK consider sub domination naming from here: https://archive.litecointalk.org/index.php?topic=19444.0

Maybe do a poll?

**Comment by losh11** [comment]
utACK

**Comment by BlankSteve** [comment]
The lumen is a measure of light.  Litecoin is lite in the sense of....new ideas to assimilate.
Like having one thousand "cents" instead of a hundred cents.
Thousands is shortened to a "thowie".
Honey for hundreds is just for fun because it rhymes with the "one".

**Pull request merged**
