### PR TITLE
Litecoin: Zeitgeist2 bool fshift bnNew.bits()

### PR DESCRIPTION
**Pull request by romanornr**
Hi, 

Maybe this magical number ````235````, I'm not sure yet but maybe use ````params.powLimit```` .
Assuming other Altcoins often fork Litecoin source code, this seems may seem a bit cleaner.

### CODE REVIEW

**Comment by shaolinfry** [comment]
Please squash to 1 commit and rebase for 0.14-dev branch

**Comment by romanornr** [comment]
Sorry I didn't saw this message. I can fork Litecoin and git checkout to 0.14-dev and push it to my fork. 

But to make the pull request, I only see the master branch and 0.13, not the 0.14-dev branch

**Comment by losh11** [comment]
Master branch is 0.14-dev

**Comment by romanornr** [comment]
Guess I lack some github lol
I made a new clean pull request here: https://github.com/litecoin-project/litecoin/pull/337

**Pull request closed without merging**
