### PR TITLE
Litecoin: enable support for SSE2 instructions in scrypt via configure --enable-sse2

### PR DESCRIPTION
**Pull request by romanornr**
Hi, 

I think SSE2 is missing for Litecoin. 
Right now I have this implementation working for Viacoin.
The implementation works fine for my Arch Linux installation. (Not tested on windows or Mac)
[https://github.com/romanornr/viacoin/tree/0.13-dev](url)

I think this works fine for Litecoin too but the Travis tests will break !  So that needs to be modified.
So if someone could review this, that would be great.

### CODE REVIEW

**Comment by shaolinfry** [comment]
This might be better as --disable-sse2 and on  by default

**Comment by shaolinfry** [comment]
@romanornr Travis is unhappy.

**Comment by romanornr** [comment]
@shaolinfry I'm aware that Travis is unhappy.
Already pointed out
screenshot from 2017-05-13 20-13-32

I haven't figured out yet on how to fix the travis tests.
I will try to fix the travis tests but let me know if you guys figured it out.

**Comment by shaolinfry** [comment]
@romanornr Maybe you need to adjust travis to sudo apt-get install libc6-dev see https://docs.travis-ci.com/user/installing-dependencies/

**Comment by MarvinOl** [comment]
There's a typo in src/crypto/scrypt.h change:
 #if defined(USE_SSE2)
+#inlude <string>

**Comment by romanornr** [comment]
@MarvinOl thanks. Just made a commit to fix the typo.

**Comment by shaolinfry** [comment]
Same travis problems though.... any luck solving those?

**Comment by romanornr** [comment]
No I didn't @shaolinfry I tried llibgcc-4.8-dev and other versions in different variations.
This is something I tried: https://github.com/viacoin/viacoin/commit/71a0f318e6a6ee960e749a22caa2ae467421c2a0

**Comment by MarvinOl** [comment]
A comment about speed improvements this brings. This is by no means pointless to implement today (some might say that modern CPUs are fast and compilers optimized).

I modified scrypt_test.ccp to only run either SSE2 or non-SSE2 hashing 10000 times. On my low power Intel Atom J2900 CPU the SSE2 version is over 2x faster (42 vs 18 seconds, just pasting one, the results are stable over multiple runs):
# time ./test_litecoin --run_test=scrypt_tests
Running 1 test case...

*** No errors detected
41.942u 0.002s 0:42.06 99.7%    9063+838k 54+0io 532pf+0w

SSE2 enabled:
18.880u 0.008s 0:18.91 99.8%    9054+837k 2+0io 389pf+0w

**Comment by romanornr** [comment]
@MarvinOl do you have a link to your fork or modification ? Sounds intresting.

**Comment by MarvinOl** [comment]
No I just used your code to enable SSE2 and then did 2 compiles, one with it defined and one without.

And modified test_scrypt.cpp to be only one or the other, and run it 10k times:
`#if defined(USE_SSE2)
    (void) scrypt_detect_sse2();
#endif
    uint256 scrypthash;
    std::vector<unsigned char> inputbytes;
    char scratchpad[SCRYPT_SCRATCHPAD_SIZE];
    for (int j = 0; j < 10000; j++) {
    for (int i = 0; i < HASHCOUNT; i++) {
        inputbytes = ParseHex(inputhex[i]);
#if defined(USE_SSE2)
        // Test SSE2 scrypt
        scrypt_1024_1_1_256_sp_sse2((const char*)&inputbytes[0], BEGIN(scrypthash), scratchpad);
        BOOST_CHECK_EQUAL(scrypthash.ToString().c_str(), expected[i]);
#else
        // Test generic scrypt
        scrypt_1024_1_1_256_sp_generic((const char*)&inputbytes[0], BEGIN(scrypthash), scratchpad);
        BOOST_CHECK_EQUAL(scrypthash.ToString().c_str(), expected[i]);
#endif
    }
    }
`

**Comment by romanornr** [comment]
Ooh I misunderstood. Thought you had an improvement for SSE2.

In that case, yeah I was aware. It's indeed 2x faster with SSE2. So this is definitely great.

**Comment by shaolinfry** [comment]
Any more progress with fixing Travis here?

**Comment by shaolinfry** [comment]
Needs rebase onto master.

**Comment by romanornr** [comment]
Ok, I will do it.

**Comment by shaolinfry** [comment]
*bump*

**Comment by romanornr** [comment]
Please close this one. Here is the follow-up https://github.com/litecoin-project/litecoin/pull/362

**Comment by thrasher-** [comment]
Closed in favor of https://github.com/litecoin-project/litecoin/pull/362

**Pull request closed without merging**
