### PR TITLE
Litecoin: Fix checkblock bench test

### PR DESCRIPTION
**Pull request by thrasher-**
Fixes https://github.com/litecoin-project/litecoin/issues/350

https://github.com/thrasher-/litecoin-tools/tree/master/biggest 
This tool was used to find the biggest block and the largest amount of transactions ever in the Litecoin blockchain. Block 878439 was chosen as it contains the most transactions in a block and has a decent size of 748946 bytes.

Preserved variable names and header files to make keeping up with upstream changes easier but could make this patch amend that if needed.

### CODE REVIEW

**Comment by shaolinfry** [comment]
tACK

**Comment by janstary** [comment]
Theis does _not_ fix https://github.com/litecoin-project/litecoin/issues/350 (has anyone tested that it does?). `bench_litecoin` dumps core on OpenBSD 6.1 as it did before.

https://github.com/litecoin-project/litecoin/commit/16ebb1a90b922deb4d626f2a30f0515ffbb7a52e adds a _comment_ to https://github.com/litecoin-project/litecoin/commit/16ebb1a90b922deb4d626f2a30f0515ffbb7a52e#diff-0ea91c22ef3455fe546fa45ea0e8a03a - how is that supposed to fix it?

**Comment by thrasher-** [comment]
@janstary yes it does work..

assertion "CheckBlock(block, validationState, params)" failed: file "bench/checkblock.cpp", line 51, function "DeserializeAndCheckBlockTest"
Abort trap (core dumped)

Was the particular error, if you look at the commit properly you will see that there was an actual file replaced too. "src/bench/data/block413567.raw 100644 → 100755"

It has been tested and works as expected:

```
./src/bench/bench_litecoin 
#Benchmark,count,min,max,average,min_cycles,max_cycles,average_cycles
Base58CheckEncode,360448,0.000002983033482,0.000003100838512,0.000003006653225,11954,12427,12049
Base58Decode,983040,0.000001026259270,0.000001087639248,0.000001036857187,4112,4358,4155
Base58Encode,524288,0.000001875239832,0.000002048596798,0.000001922557658,7515,8209,7704
BenchLockedPool,640,0.001669969409704,0.001732379198074,0.001681006327271,6692569,6942591,6736784
CCheckQueueSpeed,22528,0.000036629382521,0.000048549263738,0.000046020024456,146795,194567,184429
CCheckQueueSpeedPrevectorJob,1536,0.000639101490378,0.000880315899849,0.000664895245185,2561267,3528093,2664627
CCoinsCaching,163840,0.000006359361578,0.000006590213161,0.000006427741027,25485,26410,25759
CoinSelection,768,0.001375690102577,0.001398142427206,0.001383738281826,5513297,5603123,5545458
DeserializeAndCheckBlockTest,96,0.010511517524719,0.013772964477539,0.010910145938396,42125980,55195210,43723400
DeserializeBlockTest,144,0.006988048553467,0.007183119654655,0.007066334287326,28004755,28786785,28318948
FastRandom_1bit,896,0.001150000840425,0.001212891191244,0.001160940953663,4608741,4860768,4652572
FastRandom_32bit,144,0.007142692804337,0.007247090339661,0.007167840997378,28625122,29044413,28725782
MempoolEviction,49152,0.000021666986868,0.000022461172193,0.000021866513028,86832,90014,87632
PrevectorClear,5632,0.000181070528924,0.000185877084732,0.000182335561311,725658,744917,730726
PrevectorDestructor,6144,0.000161861535162,0.000179124996066,0.000169838080183,648673,717865,680641
RIPEMD160,512,0.001963846385479,0.002163030207157,0.001980513799936,7870172,8668585,7937084
RollingBloom-refresh,1,0.000108000000000,0.000108000000000,0.000108000000000
RollingBloom-refresh,1,0.000089000000000,0.000089000000000,0.000089000000000
RollingBloom-refresh,1,0.000090000000000,0.000090000000000,0.000090000000000
RollingBloom-refresh,1,0.000090000000000,0.000090000000000,0.000090000000000
RollingBloom-refresh,1,0.000092000000000,0.000092000000000,0.000092000000000
RollingBloom-refresh,1,0.000089000000000,0.000089000000000,0.000089000000000
RollingBloom-refresh,1,0.000088000000000,0.000088000000000,0.000088000000000
RollingBloom-refresh,1,0.000089000000000,0.000089000000000,0.000089000000000
RollingBloom-refresh,1,0.000099000000000,0.000099000000000,0.000099000000000
RollingBloom-refresh,1,0.000171000000000,0.000171000000000,0.000171000000000
RollingBloom-refresh,1,0.000090000000000,0.000090000000000,0.000090000000000
RollingBloom-refresh,1,0.000089000000000,0.000089000000000,0.000089000000000
RollingBloom-refresh,1,0.000089000000000,0.000089000000000,0.000089000000000
RollingBloom-refresh,1,0.000089000000000,0.000089000000000,0.000089000000000
RollingBloom-refresh,1,0.000089000000000,0.000089000000000,0.000089000000000
RollingBloom-refresh,1,0.000102000000000,0.000102000000000,0.000102000000000
RollingBloom-refresh,1,0.000089000000000,0.000089000000000,0.000089000000000
RollingBloom-refresh,1,0.000088000000000,0.000088000000000,0.000088000000000
RollingBloom-refresh,1,0.000089000000000,0.000089000000000,0.000089000000000
RollingBloom-refresh,1,0.000095000000000,0.000095000000000,0.000095000000000
RollingBloom-refresh,1,0.000089000000000,0.000089000000000,0.000089000000000
RollingBloom-refresh,1,0.000089000000000,0.000089000000000,0.000089000000000
RollingBloom-refresh,1,0.000088000000000,0.000088000000000,0.000088000000000
RollingBloom-refresh,1,0.000089000000000,0.000089000000000,0.000089000000000
RollingBloom-refresh,1,0.000089000000000,0.000089000000000,0.000089000000000
RollingBloom-refresh,1,0.000096000000000,0.000096000000000,0.000096000000000
RollingBloom-refresh,1,0.000095000000000,0.000095000000000,0.000095000000000
RollingBloom-refresh,1,0.000096000000000,0.000096000000000,0.000096000000000
RollingBloom-refresh,1,0.000089000000000,0.000089000000000,0.000089000000000
RollingBloom-refresh,1,0.000096000000000,0.000096000000000,0.000096000000000
RollingBloom,1835008,0.000000551499397,0.000000579429980,0.000000565038395,2210,2322,2264
SHA1,448,0.001418344676495,0.004331186413765,0.002295167318412,5684093,17357619,9198098
SHA256,256,0.003734618425369,0.004359260201454,0.003948370926082,14966885,17470058,15823456
SHA256_32b,4,0.263343930244446,0.265676021575928,0.264509975910187,1055375703,1064719736,1060047719
SHA512,448,0.002360500395298,0.002497375011444,0.002395913004875,9460003,10008466,9601837
SipHash_32b,48,0.021576225757599,0.023521482944489,0.022143354018529,86467863,94265032,88741520
Sleep100ms,10,0.100270509719849,0.100344061851501,0.100290703773499,401841657,402138833,401924262
Trig,31457280,0.000000018381115,0.000000034116738,0.000000032624818,73,136,130
VerifyScriptBench,8192,0.000121400225908,0.000162632670254,0.000129186024424,486524,651762,517724
thrasher@ubuntu:~/Desktop/litecoin$ 
```

**Comment by janstary** [comment]
Yes, it failed on the block we had before, but it does not fails on this block.
But you would not call that a fix, right?

(Currently, it dumps core on Trig, see separate issue).

**Pull request merged**
